CREATE TABLE empresa (
	id bigint generated by default as identity primary key,
	cnpj VARCHAR (14) NOT NULL UNIQUE,
	nome_fantasia VARCHAR (120) NOT NULL,
	email VARCHAR (120) NOT NULL,
	telefone varchar(20) NOT NULL,
	cep VARCHAR (8) NOT NULL,
	uf VARCHAR (2) NOT NULL,
	cidade VARCHAR (50),
	logradouro VARCHAR (120),
	bairro VARCHAR (50),
	ativo BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE fornecedor (
	id bigint generated by default as identity primary key,
	tipo_pessoa VARCHAR (2),
	cpf_cnpj VARCHAR (14) NOT NULL UNIQUE,
	nome VARCHAR (120) NOT NULL,
	email VARCHAR (120) NOT NULL,
	telefone varchar(20) NOT NULL
	cep VARCHAR (8) NOT NULL,
	uf VARCHAR (2) NOT NULL,
	cidade VARCHAR (50),
	logradouro VARCHAR (120),
	bairro VARCHAR (50),
	rg VARCHAR (20),
	data_nascimento DATE,

	ativo BOOLEAN NOT NULL DEFAULT true,

	CONSTRAINT ck_tipo_pessoa CHECK (tipo_pessoa in ('PF','PJ'))
);

CREATE INDEX idx_fornecedor_nome on fornecedor (nome);
CREATE INDEX idx_fornecedor_cpf_cnpj ON fornecedor (cpf_cnpj);

CREATE TABLE empresa_fornecedor (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	empresa_id BIGINT NOT NULL REFERENCES empresa(id),
	fornecedor_id BIGINT NOT NULL REFERENCES fornecedor(id),
	data_cadastro TIMESTAMP NOT NULL DEFAULT now(),
	ativo BOOLEAN NOT NULL DEFAULT true,
	CONSTRAINT uk_empresa_fornecedor UNIQUE (empresa_id, fornecedor_id)
);